name: shyft
channels:
  - conda-forge
  - defaults
dependencies:
  - bleach=2.0.0=py36_0
  - entrypoints=0.2.3=py36_1
  - gmp=6.1.2=0
  - html5lib=0.999999999=py36_0
  - ipykernel=4.7.0=py36_0
  - ipython=6.2.1=py36_0
  - ipywidgets=7.0.5=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_0
  - jupyter_client=5.1.0=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.4.0=py_0
  - markupsafe=1.0=py36_0
  - mistune=0.8.3=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - notebook=5.2.2=py36_1
  - pandas=0.21.0=py36_0
  - pandoc=2.0.4=0
  - pandocfilters=1.4.1=py36_0
  - pyzmq=16.0.2=py36_2
  - qtconsole=4.3.1=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - webencodings=0.5=py36_0
  - widgetsnbextension=3.0.8=py36_0
  - zeromq=4.2.1=1
  - asn1crypto=0.23.0=py36h4639342_0
  - bzip2=1.0.6=h6d464ef_2
  - ca-certificates=2017.08.26=h1d4fec5_0
  - cairo=1.14.10=hdf128ce_6
  - certifi=2017.11.5=py36hf29ccca_0
  - cffi=1.11.2=py36h2825082_0
  - chardet=3.0.4=py36h0f667ec_1
  - cryptography=2.1.4=py36hd09be54_0
  - curl=7.55.1=h78862de_4
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.10.22=h3b5a359_0
  - decorator=4.1.2=py36hd076ac8_0
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - freexl=1.0.4=hf32cdb2_5
  - gdal=2.2.2=py36hc209d97_1
  - geos=3.6.2=heeff764_2
  - giflib=5.1.4=h26a3ec6_1
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.8.18=h6792536_1
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py36h82fb2a8_1
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jbig=2.1=hdba287a_0
  - jedi=0.11.0=py36hf290c5b_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.12.1=ha6a3662_2
  - kealib=1.4.7=h5472223_5
  - krb5=1.14.2=hcdc1b81_6
  - libboost=1.65.1=h4055789_3
  - libdap4=3.19.0=h8c95237_1
  - libdynd=0.7.2=0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgdal=2.2.2=h6bd4d82_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libkml=1.3.0=h9d32c78_3
  - libnetcdf=4.4.1.1=h97d33d9_8
  - libpng=1.6.32=hbd3595f_4
  - libpq=9.6.6=h4e02ad2_0
  - libsodium=1.0.15=hf101ebd_0
  - libspatialite=4.3.0a=h72746d6_18
  - libssh2=1.8.0=h2d05a93_3
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.4=h2e8b1d7_6
  - matplotlib=2.1.0=py36hba5de38_0
  - mkl=2018.0.1=h19d6760_4
  - ncurses=6.0=h9df7e31_2
  - netcdf4=1.3.1=py36h771828c_2
  - nose=1.3.7=py36hcdf7029_2
  - numpy=1.13.3=py36ha12f23b_0
  - openjpeg=2.2.0=h622c3cc_2
  - openssl=1.0.2n=hb7f436b_0
  - parso=0.1.0=py36h2b61f4d_0
  - patchelf=0.9=hf79760b_2
  - pcre=8.41=hc27e229_1
  - pexpect=4.3.0=py36h673ed17_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=9.0.1=py36h6c6f9ce_4
  - pixman=0.34.0=hceecf20_3
  - poppler=0.60.1=hc909a00_0
  - poppler-data=0.4.8=hf2eda46_0
  - proj4=4.9.3=hc8507d1_7
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36hf9f622e_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=17.5.0=py36h20ba746_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyproj=1.9.5.1=py36_0
  - pyqt=5.6.0=py36h0386399_5
  - pysocks=1.6.7=py36hd97a5b1_1
  - python=3.6.3=h6c0c0dc_5
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2017.3=py36h63b9c63_0
  - pyyaml=3.12=py36hafb9ca4_1
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - redis=4.0.2=h6805cf8_0
  - requests=2.18.4=py36he2e5f8d_1
  - scipy=1.0.0=py36hbf646e7_0
  - setuptools=36.5.0=py36he42e2e1_0
  - shapely=1.6.2=py36hfae5896_0
  - simplegeneric=0.8.1=py36h2cb9092_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sphinx_rtd_theme=0.2.4=py36_0
  - sqlite=3.20.1=hb898158_2
  - tk=8.6.7=hc745277_3
  - tornado=4.5.2=py36h1283b2a_0
  - traitlets=4.3.2=py36h674d592_0
  - urllib3=1.22=py36hbe7ace6_0
  - util-linux=2.21=0
  - wcwidth=0.1.7=py36hdf4376a_0
  - wheel=0.30.0=py36hfd4bba0_1
  - xerces-c=3.2.0=h524ea4d_2
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - alabaster==0.7.10
    - babel==2.5.3
    - breathe==4.7.3
    - docutils==0.14
    - imagesize==0.7.1
    - nbsphinx==0.3.0
    - snowballstemmer==1.2.1
    - sphinx==1.6.6
    - sphinxcontrib-websupport==1.0.1
prefix: /home/johnbur/.conda/envs/shyft

